# model
model_name_or_path: 'llama-13B'
cache_dir: '/remote-home/share/llama'
# data
dataset_name: 'openbookqa'
refresh: false
data_tag: 'natural'
max_length: 256
#prompt_type: 'brown'
#few_shot_size: 8
#in_context_learning: true
# collie
# trainer
tag: 'finetune'
output_dir: 'outputs'
overwrite_output_dir: true
do_train: true
do_eval: true
evaluation_strategy: 'epoch'
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 0.01
weight_decay: 0
num_train_epochs: 10
lr_scheduler_type: 'linear'
warmup: 0.05
clip_grad_norm: 1.0
#clip_grad_value: 1.0
#clip_loss_value: 5.0
log_level: 'info'
logging_steps: 1
save_strategy: 'no'
save_total_limit: 0
seed: 42
fp16: true
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'acc'
optim: 'sgd'
#group_by_length: true
report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: false
predict_with_generate: true
#length_normalization: false
#unconditional_normalization: true